/*
=====================
Database Exploration
=====================
*/

-- Retrieving list of all tables in the database
SELECT 
    TABLE_CATALOG, 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES;

-- Retrieving all columns for a specific table
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE, 
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold.dim_customers';

/*
======================
Dimensions Exploration
========================
*/
USE DataWarehouseAnalytics;
Select * From [gold.fact_sales]
-- Retrieve a list of unique countries from which customers originate
SELECT DISTINCT 
    country
FROM [gold.dim_customers]
ORDER BY country;

-- Retrieve a list of unique categories, subcategories, and products
SELECT DISTINCT 
    category, 
    subcategory, 
    product_name 
FROM [gold.dim_products]
ORDER BY category, subcategory, product_name;
--Retrieving list of Product_ids 
SELECT DISTINCT
product_key
FROM [gold.fact_sales]
ORDER BY product_key

/*
======================
Date Range Exploration 
========================
*/

-- First and Last order date;total duration in months
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM [gold.fact_sales];

-- Youngest and Oldest customer based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM [gold.dim_customers];

/*
===========
Key Metrics
==============
*/

-- Total Sales
SELECT SUM(sales_amount) AS total_sales FROM [gold.fact_sales]

-- Number of items sold
SELECT SUM(quantity) AS total_quantity FROM [gold.fact_sales]

-- Average selling price
SELECT AVG(price) AS avg_price FROM [gold.fact_sales]

-- Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM [gold.fact_sales]
SELECT COUNT(DISTINCT order_number) AS total_orders FROM [gold.fact_sales]

-- Total number of products
SELECT COUNT(product_name) AS total_products FROM [gold.dim_products]

-- Total number of customers
SELECT COUNT(customer_key) AS total_customers FROM [gold.dim_customers];

-- Total number of customers [Order Placed]
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM [gold.fact_sales];

-- Overall Report depicting all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM [gold.fact_sales]
UNION ALL
SELECT 'Average Price', AVG(price) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM [gold.dim_products]
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM [gold.dim_customers];

/*
==================
Magnitude Analysis
=====================
*/

-- Total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM [gold.dim_customers]
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM [gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC;

-- Total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM [gold.dim_products]
GROUP BY category
ORDER BY total_products DESC;

-- Average costs in each category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM [gold.dim_products]
GROUP BY category
ORDER BY avg_cost DESC;

-- Total revenue generated for each category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_products] p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Distribution of sold items across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

/*
================
Ranking Analysis
==================
*/

-- Top 5 products Generating the Highest Revenue
SELECT *
FROM (
    SELECT
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM [gold.fact_sales] f
    LEFT JOIN [gold.dim_products] p
        ON p.product_key = f.product_key
    GROUP BY p.product_name
) AS ranked_products
WHERE rank_products <= 5;

-- The 5 worst-performing products in terms of sales
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_products] p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- Top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The 5 customers with the fewest orders placed
SELECT TOP 5
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM [gold.fact_sales] f
LEFT JOIN [gold.dim_customers] c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ;
